### PR TITLE
scrcpy v1.17

### PR DESCRIPTION
**Pull request by drauggres**
- [x] ~~update server to [`v1.17-ws`](https://github.com/NetrisTV/scrcpy/releases/tag/1.17-ws)~~
- [x] update server to [`v1.17-ws1`](https://github.com/NetrisTV/scrcpy/releases/tag/v1.17-ws1)
- [x] add [`encoderName`](https://github.com/Genymobile/scrcpy#encoder) to VideoSettings interface
- [x] add [`codecOptions`](https://github.com/Genymobile/scrcpy/blob/ce43fad645d4eb30f322dbeb50d5197601564931/app/src/cli.c#L29-L36) to VideoSettings interface
- [x] add [`displayId`](https://github.com/Genymobile/scrcpy#display) to VideoSettings interface
- [x] add UI controls for `encoderName`
- [x] add UI controls for `codecOptions`
- [x] add UI controls for `displayId`

### CODE REVIEW

**Comment by sai-tirunagiri** [comment]
when can we have this pull request approved? we have been waiting for displayId on video settings.

**Comment by drauggres** [comment]
Hi, @sai-tirunagiri.

As you can see, I haven't finished UI, so there is no way to control any of these "new" options.
I pushed everything I have at the moment to [this branch](https://github.com/drauggres/ws-scrcpy/tree/feature/configure_dialog) in my fork; you can try it, but it is "work in progress".

I will continue to work on this, but there is no ETA.

**Comment by sai-tirunagiri** [comment]
Thank you and this is a great project.

**Comment by drauggres** [comment]
Just figured how to test `displayId`. Apparentely it doesn't work with my fork.

**Pull request merged**
