### PR TITLE
fix: dependencies

### LINKED ISSUE #213: compilation issues with ios mjpeg when latest code is pulled
ERROR in ./src/server/appl-device/services/WDARunner.ts
    Module not found: Error: Can't resolve 'appium-support' in '/Users/home/ws-scrcpy/src/server/appl-device/services'
     @ ./src/server/appl-device/services/WDARunner.ts 9:23-48
     @ ./src/server/appl-device/mw/WebDriverAgentProxy.ts
     @ ./src/server/index.ts
    
    ERROR in ./src/server/index.ts
    Module not found: Error: Can't resolve 'npmlog' in '/Users/home/ws-scrcpy/src/server'
     @ ./src/server/index.ts 60:96-113

### PR DESCRIPTION
**Pull request by drauggres**
add @types/webpack@4
lock "@types/mini-css-extract-plugin" to ^0.9.1
fix missing appium-support dependency

regenerate package-lock.json

fix #213

### CODE REVIEW

**Comment by drauggres** [comment]
@krishtoautomate 
Please try to build and run. I was able to build it with `"INCLUDE_APPL": true`, but I can't verify that it actually works since I don't have access to any macs/iphones anymore.

**Comment by krishtoautomate** [comment]
> ws-scrcpy@0.8.0-dev start
> node ./index.js

Cannot set property level of #<Object> which has only a getter

Received signal 1

**Comment by drauggres** [comment]
Actually compilation was successful, it failed to change log level for `npmlog` after start.
Should be fine now.

Please try again.

**Comment by krishtoautomate** [comment]
same issue not resolved.

commented below lines worked:

    // Hack to reduce log-level of appium libs
    // const npmlog = await import('npmlog');
    // npmlog.level = 'warn';
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    // (global as any)._global_npmlog = npmlog;

**Comment by drauggres** [comment]
With the last commit it should be:
```typescript
const { default: npmlog } = await import('npmlog');
```
not 
```typescript
const npmlog = await import('npmlog');
```

**Comment by krishtoautomate** [comment]
Worked.

    // Hack to reduce log-level of appium libs
    const {default : npmlog }= await import('npmlog');
    npmlog.level = 'warn';
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (global as any)._global_npmlog = npmlog;

thanks

**Pull request merged**
